version: '3'
services:
  react-app:
    build:
      context: .
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    ports:
      - "3002:80"
    restart: always
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
